---
- name: Cleanup from Nginx
  hosts: all
  become: true
  tasks:
    - name: Ensure Nginx service is stopped.
      ansible.builtin.systemd:
        name: nginx
        state: stopped
        enabled: false
        daemon_reload: true
      ignore_errors: true
    - name: Ensure Nginx is removed.
      ansible.builtin.apt:
        name: nginx
        state: absent
        purge: true
        autoremove: true
      register: result
      retries: 6
      delay: 30
      until: result is not failed
    - name: Remove html artifacts.
      vars:
        nginx_html_path: /var/www/html
      ansible.builtin.file:
        name: "{{ nginx_html_path }}/{{ item }}"
        state: absent
      loop:
        - 403.html
        - 404.html
        - 500.html
        - index.nginx-debian.html
        - underconstruction.html
