---
- name: Install NGINX server
  hosts: all
  become: true
  gather_facts: true
  vars_files:
    - ./vars.yml

  roles:
    - astra.nginx.nginx

  tasks:
    - name: Create index.html
      ansible.builtin.template:
        src: templates/index.html.j2
        dest: /var/www/html/index.nginx-debian.html
        mode: 0644
        owner: www-data
        group: www-data
